
import finalsproject.BillingSystem1;
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author James
 */
public class numBtn extends javax.swing.JFrame {

    /**
     * Creates new form numBtn
     */
    Color clkColor, white, red;
    public numBtn() {
        initComponents();
         clkColor = new Color(76,44,23);
        white = new Color(255,255,255);
        red = new Color(242,5,5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        n7P = new javax.swing.JPanel();
        n7 = new javax.swing.JLabel();
        n8P = new javax.swing.JPanel();
        n8 = new javax.swing.JLabel();
        n9P = new javax.swing.JPanel();
        n9 = new javax.swing.JLabel();
        n4P = new javax.swing.JPanel();
        n4 = new javax.swing.JLabel();
        n1P = new javax.swing.JPanel();
        n1 = new javax.swing.JLabel();
        n5P = new javax.swing.JPanel();
        n5 = new javax.swing.JLabel();
        n2P = new javax.swing.JPanel();
        n2 = new javax.swing.JLabel();
        n6P = new javax.swing.JPanel();
        n6 = new javax.swing.JLabel();
        n3P = new javax.swing.JPanel();
        n3 = new javax.swing.JLabel();
        n0P = new javax.swing.JPanel();
        n0 = new javax.swing.JLabel();
        delP = new javax.swing.JPanel();
        del = new javax.swing.JLabel();
        clrP = new javax.swing.JPanel();
        clr = new javax.swing.JLabel();
        n0P1 = new javax.swing.JPanel();
        entr = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        num = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 575));

        jPanel1.setBackground(new java.awt.Color(76, 44, 23));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 540));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23), 2));

        n7P.setBackground(new java.awt.Color(255, 255, 255));
        n7P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        n7.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        n7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n7.setText("7");
        n7.setPreferredSize(new java.awt.Dimension(16, 16));
        n7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout n7PLayout = new javax.swing.GroupLayout(n7P);
        n7P.setLayout(n7PLayout);
        n7PLayout.setHorizontalGroup(
            n7PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        n7PLayout.setVerticalGroup(
            n7PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        n8P.setBackground(new java.awt.Color(255, 255, 255));
        n8P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        n8.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        n8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n8.setText("8");
        n8.setPreferredSize(new java.awt.Dimension(16, 16));
        n8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout n8PLayout = new javax.swing.GroupLayout(n8P);
        n8P.setLayout(n8PLayout);
        n8PLayout.setHorizontalGroup(
            n8PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n8, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        n8PLayout.setVerticalGroup(
            n8PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n8, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        n9P.setBackground(new java.awt.Color(255, 255, 255));
        n9P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        n9.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        n9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n9.setText("9");
        n9.setPreferredSize(new java.awt.Dimension(16, 16));
        n9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout n9PLayout = new javax.swing.GroupLayout(n9P);
        n9P.setLayout(n9PLayout);
        n9PLayout.setHorizontalGroup(
            n9PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        n9PLayout.setVerticalGroup(
            n9PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        n4P.setBackground(new java.awt.Color(255, 255, 255));
        n4P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        n4.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        n4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n4.setText("4");
        n4.setPreferredSize(new java.awt.Dimension(16, 16));
        n4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout n4PLayout = new javax.swing.GroupLayout(n4P);
        n4P.setLayout(n4PLayout);
        n4PLayout.setHorizontalGroup(
            n4PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        n4PLayout.setVerticalGroup(
            n4PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        n1P.setBackground(new java.awt.Color(255, 255, 255));
        n1P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        n1.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n1.setText("1");
        n1.setPreferredSize(new java.awt.Dimension(16, 16));
        n1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout n1PLayout = new javax.swing.GroupLayout(n1P);
        n1P.setLayout(n1PLayout);
        n1PLayout.setHorizontalGroup(
            n1PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        n1PLayout.setVerticalGroup(
            n1PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        n5P.setBackground(new java.awt.Color(255, 255, 255));
        n5P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        n5.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        n5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n5.setText("5");
        n5.setPreferredSize(new java.awt.Dimension(16, 16));
        n5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout n5PLayout = new javax.swing.GroupLayout(n5P);
        n5P.setLayout(n5PLayout);
        n5PLayout.setHorizontalGroup(
            n5PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        n5PLayout.setVerticalGroup(
            n5PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        n2P.setBackground(new java.awt.Color(255, 255, 255));
        n2P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        n2.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        n2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n2.setText("2");
        n2.setPreferredSize(new java.awt.Dimension(16, 16));
        n2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout n2PLayout = new javax.swing.GroupLayout(n2P);
        n2P.setLayout(n2PLayout);
        n2PLayout.setHorizontalGroup(
            n2PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        n2PLayout.setVerticalGroup(
            n2PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        n6P.setBackground(new java.awt.Color(255, 255, 255));
        n6P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        n6.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        n6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n6.setText("6");
        n6.setPreferredSize(new java.awt.Dimension(16, 16));
        n6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout n6PLayout = new javax.swing.GroupLayout(n6P);
        n6P.setLayout(n6PLayout);
        n6PLayout.setHorizontalGroup(
            n6PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        n6PLayout.setVerticalGroup(
            n6PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        n3P.setBackground(new java.awt.Color(255, 255, 255));
        n3P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        n3.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        n3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n3.setText("3");
        n3.setPreferredSize(new java.awt.Dimension(16, 16));
        n3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout n3PLayout = new javax.swing.GroupLayout(n3P);
        n3P.setLayout(n3PLayout);
        n3PLayout.setHorizontalGroup(
            n3PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        n3PLayout.setVerticalGroup(
            n3PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        n0P.setBackground(new java.awt.Color(255, 255, 255));
        n0P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        n0.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        n0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n0.setText("0");
        n0.setPreferredSize(new java.awt.Dimension(16, 16));
        n0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n0MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n0MousePressed(evt);
            }
        });

        javax.swing.GroupLayout n0PLayout = new javax.swing.GroupLayout(n0P);
        n0P.setLayout(n0PLayout);
        n0PLayout.setHorizontalGroup(
            n0PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n0, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        n0PLayout.setVerticalGroup(
            n0PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n0, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        delP.setBackground(new java.awt.Color(255, 255, 255));
        delP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        del.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        del.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        del.setText("del");
        del.setPreferredSize(new java.awt.Dimension(16, 16));
        del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delMousePressed(evt);
            }
        });

        javax.swing.GroupLayout delPLayout = new javax.swing.GroupLayout(delP);
        delP.setLayout(delPLayout);
        delPLayout.setHorizontalGroup(
            delPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(del, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        delPLayout.setVerticalGroup(
            delPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(del, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        clrP.setBackground(new java.awt.Color(255, 255, 255));
        clrP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        clr.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        clr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clr.setText("C");
        clr.setPreferredSize(new java.awt.Dimension(16, 16));
        clr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clrMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clrMousePressed(evt);
            }
        });

        javax.swing.GroupLayout clrPLayout = new javax.swing.GroupLayout(clrP);
        clrP.setLayout(clrPLayout);
        clrPLayout.setHorizontalGroup(
            clrPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clr, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        clrPLayout.setVerticalGroup(
            clrPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clr, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        n0P1.setBackground(new java.awt.Color(76, 44, 23));
        n0P1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));

        entr.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        entr.setForeground(new java.awt.Color(255, 255, 255));
        entr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entr.setText("ENTER");
        entr.setPreferredSize(new java.awt.Dimension(16, 16));
        entr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                entrMousePressed(evt);
            }
        });

        javax.swing.GroupLayout n0P1Layout = new javax.swing.GroupLayout(n0P1);
        n0P1.setLayout(n0P1Layout);
        n0P1Layout.setHorizontalGroup(
            n0P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entr, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );
        n0P1Layout.setVerticalGroup(
            n0P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        num.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        num.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        num.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));
        num.setPreferredSize(new java.awt.Dimension(218, 40));
        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(n0P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(n7P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(n8P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(n9P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(n4P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(n5P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(n6P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(n1P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(n2P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(n3P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(n0P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(delP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clrP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n7P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n8P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n9P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(n6P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(n3P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(n5P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(n2P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(n0P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(n4P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(n1P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clrP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(n0P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n7MouseClicked
        // TODO add your handling code here:
        String newNum = num.getText();
        num.setText(newNum + "7");
    }//GEN-LAST:event_n7MouseClicked

    private void n7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n7MousePressed
        // TODO add your handling code here:
        clrP.setBackground(white);
        clr.setForeground(clkColor);

        delP.setBackground(white);
        del.setForeground(clkColor);

        n7P.setBackground(clkColor);
        n7.setForeground(white);

        n1P.setBackground(white);
        n1.setForeground(clkColor);

        n2P.setBackground(white);
        n2.setForeground(clkColor);

        n3P.setBackground(white);
        n3.setForeground(clkColor);

        n4P.setBackground(white);
        n4.setForeground(clkColor);

        n5P.setBackground(white);
        n5.setForeground(clkColor);

        n6P.setBackground(white);
        n6.setForeground(clkColor);

        n0P.setBackground(white);
        n0.setForeground(clkColor);

        n8P.setBackground(white);
        n8.setForeground(clkColor);

        n9P.setBackground(white);
        n9.setForeground(clkColor);
    }//GEN-LAST:event_n7MousePressed

    private void n8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n8MouseClicked
        // TODO add your handling code here:
        String newNum = num.getText();
        num.setText(newNum + "8");
    }//GEN-LAST:event_n8MouseClicked

    private void n8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n8MousePressed
        // TODO add your handling code here:
        clrP.setBackground(white);
        clr.setForeground(clkColor);

        delP.setBackground(white);
        del.setForeground(clkColor);

        n8P.setBackground(clkColor);
        n8.setForeground(white);

        n1P.setBackground(white);
        n1.setForeground(clkColor);

        n2P.setBackground(white);
        n2.setForeground(clkColor);

        n3P.setBackground(white);
        n3.setForeground(clkColor);

        n4P.setBackground(white);
        n4.setForeground(clkColor);

        n5P.setBackground(white);
        n5.setForeground(clkColor);

        n6P.setBackground(white);
        n6.setForeground(clkColor);

        n7P.setBackground(white);
        n7.setForeground(clkColor);

        n0P.setBackground(white);
        n0.setForeground(clkColor);

        n9P.setBackground(white);
        n9.setForeground(clkColor);
    }//GEN-LAST:event_n8MousePressed

    private void n9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n9MouseClicked
        // TODO add your handling code here:
        String newNum = num.getText();
        num.setText(newNum + "9");
    }//GEN-LAST:event_n9MouseClicked

    private void n9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n9MousePressed
        // TODO add your handling code here:
        clrP.setBackground(white);
        clr.setForeground(clkColor);

        delP.setBackground(white);
        del.setForeground(clkColor);

        n9P.setBackground(clkColor);
        n9.setForeground(white);

        n1P.setBackground(white);
        n1.setForeground(clkColor);

        n2P.setBackground(white);
        n2.setForeground(clkColor);

        n3P.setBackground(white);
        n3.setForeground(clkColor);

        n4P.setBackground(white);
        n4.setForeground(clkColor);

        n5P.setBackground(white);
        n5.setForeground(clkColor);

        n6P.setBackground(white);
        n6.setForeground(clkColor);

        n7P.setBackground(white);
        n7.setForeground(clkColor);

        n8P.setBackground(white);
        n8.setForeground(clkColor);

        n0P.setBackground(white);
        n0.setForeground(clkColor);
    }//GEN-LAST:event_n9MousePressed

    private void n4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n4MouseClicked
        // TODO add your handling code here:
        String newNum = num.getText();
        num.setText(newNum + "4");
    }//GEN-LAST:event_n4MouseClicked

    private void n4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n4MousePressed
        // TODO add your handling code here:
        clrP.setBackground(white);
        clr.setForeground(clkColor);

        delP.setBackground(white);
        del.setForeground(clkColor);

        n4P.setBackground(clkColor);
        n4.setForeground(white);

        n1P.setBackground(white);
        n1.setForeground(clkColor);

        n2P.setBackground(white);
        n2.setForeground(clkColor);

        n3P.setBackground(white);
        n3.setForeground(clkColor);

        n0P.setBackground(white);
        n0.setForeground(clkColor);

        n5P.setBackground(white);
        n5.setForeground(clkColor);

        n6P.setBackground(white);
        n6.setForeground(clkColor);

        n7P.setBackground(white);
        n7.setForeground(clkColor);

        n8P.setBackground(white);
        n8.setForeground(clkColor);

        n9P.setBackground(white);
        n9.setForeground(clkColor);
    }//GEN-LAST:event_n4MousePressed

    private void n1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n1MouseClicked
        // TODO add your handling code here:
        String newNum = num.getText();
        num.setText(newNum + "1");
    }//GEN-LAST:event_n1MouseClicked

    private void n1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n1MousePressed
        // TODO add your handling code here:
        clrP.setBackground(white);
        clr.setForeground(clkColor);

        delP.setBackground(white);
        del.setForeground(clkColor);

        n1P.setBackground(clkColor);
        n1.setForeground(white);

        n0P.setBackground(white);
        n0.setForeground(clkColor);

        n2P.setBackground(white);
        n2.setForeground(clkColor);

        n3P.setBackground(white);
        n3.setForeground(clkColor);

        n4P.setBackground(white);
        n4.setForeground(clkColor);

        n5P.setBackground(white);
        n5.setForeground(clkColor);

        n6P.setBackground(white);
        n6.setForeground(clkColor);

        n7P.setBackground(white);
        n7.setForeground(clkColor);

        n8P.setBackground(white);
        n8.setForeground(clkColor);

        n9P.setBackground(white);
        n9.setForeground(clkColor);
    }//GEN-LAST:event_n1MousePressed

    private void n5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n5MouseClicked
        // TODO add your handling code here:
        String newNum = num.getText();
        num.setText(newNum + "5");
    }//GEN-LAST:event_n5MouseClicked

    private void n5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n5MousePressed
        // TODO add your handling code here:
        clrP.setBackground(white);
        clr.setForeground(clkColor);

        delP.setBackground(white);
        del.setForeground(clkColor);

        n5P.setBackground(clkColor);
        n5.setForeground(white);

        n1P.setBackground(white);
        n1.setForeground(clkColor);

        n2P.setBackground(white);
        n2.setForeground(clkColor);

        n3P.setBackground(white);
        n3.setForeground(clkColor);

        n4P.setBackground(white);
        n4.setForeground(clkColor);

        n0P.setBackground(white);
        n0.setForeground(clkColor);

        n6P.setBackground(white);
        n6.setForeground(clkColor);

        n7P.setBackground(white);
        n7.setForeground(clkColor);

        n8P.setBackground(white);
        n8.setForeground(clkColor);

        n9P.setBackground(white);
        n9.setForeground(clkColor);
    }//GEN-LAST:event_n5MousePressed

    private void n2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n2MouseClicked
        // TODO add your handling code here:
        String newNum = num.getText();
        num.setText(newNum + "2");
    }//GEN-LAST:event_n2MouseClicked

    private void n2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n2MousePressed
        // TODO add your handling code here:
        clrP.setBackground(white);
        clr.setForeground(clkColor);

        delP.setBackground(white);
        del.setForeground(clkColor);

        n2P.setBackground(clkColor);
        n2.setForeground(white);

        n1P.setBackground(white);
        n1.setForeground(clkColor);

        n0P.setBackground(white);
        n0.setForeground(clkColor);

        n3P.setBackground(white);
        n3.setForeground(clkColor);

        n4P.setBackground(white);
        n4.setForeground(clkColor);

        n5P.setBackground(white);
        n5.setForeground(clkColor);

        n6P.setBackground(white);
        n6.setForeground(clkColor);

        n7P.setBackground(white);
        n7.setForeground(clkColor);

        n8P.setBackground(white);
        n8.setForeground(clkColor);

        n9P.setBackground(white);
        n9.setForeground(clkColor);
    }//GEN-LAST:event_n2MousePressed

    private void n6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n6MouseClicked
        // TODO add your handling code here:
        String newNum = num.getText();
        num.setText(newNum + "6");
    }//GEN-LAST:event_n6MouseClicked

    private void n6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n6MousePressed
        // TODO add your handling code here:
        clrP.setBackground(white);
        clr.setForeground(clkColor);

        delP.setBackground(white);
        del.setForeground(clkColor);

        n6P.setBackground(clkColor);
        n6.setForeground(white);

        n1P.setBackground(white);
        n1.setForeground(clkColor);

        n2P.setBackground(white);
        n2.setForeground(clkColor);

        n3P.setBackground(white);
        n3.setForeground(clkColor);

        n4P.setBackground(white);
        n4.setForeground(clkColor);

        n5P.setBackground(white);
        n5.setForeground(clkColor);

        n0P.setBackground(white);
        n0.setForeground(clkColor);

        n7P.setBackground(white);
        n7.setForeground(clkColor);

        n8P.setBackground(white);
        n8.setForeground(clkColor);

        n9P.setBackground(white);
        n9.setForeground(clkColor);
    }//GEN-LAST:event_n6MousePressed

    private void n3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n3MouseClicked
        // TODO add your handling code here:
        String newNum = num.getText();
        num.setText(newNum + "3");
    }//GEN-LAST:event_n3MouseClicked

    private void n3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n3MousePressed
        // TODO add your handling code here:
        clrP.setBackground(white);
        clr.setForeground(clkColor);

        delP.setBackground(white);
        del.setForeground(clkColor);

        n3P.setBackground(clkColor);
        n3.setForeground(white);

        n1P.setBackground(white);
        n1.setForeground(clkColor);

        n2P.setBackground(white);
        n2.setForeground(clkColor);

        n0P.setBackground(white);
        n0.setForeground(clkColor);

        n4P.setBackground(white);
        n4.setForeground(clkColor);

        n5P.setBackground(white);
        n5.setForeground(clkColor);

        n6P.setBackground(white);
        n6.setForeground(clkColor);

        n7P.setBackground(white);
        n7.setForeground(clkColor);

        n8P.setBackground(white);
        n8.setForeground(clkColor);

        n9P.setBackground(white);
        n9.setForeground(clkColor);
    }//GEN-LAST:event_n3MousePressed

    private void n0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n0MouseClicked
        // TODO add your handling code here:
        String newNum = num.getText();
        num.setText(newNum + "0");
        if(num.getText().equals("0")){
            num.setText("");
        }
    }//GEN-LAST:event_n0MouseClicked

    private void n0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n0MousePressed
        // TODO add your handling code here:
        n0P.setBackground(clkColor);
        n0.setForeground(white);

        n1P.setBackground(white);
        n1.setForeground(clkColor);

        n2P.setBackground(white);
        n2.setForeground(clkColor);

        n3P.setBackground(white);
        n3.setForeground(clkColor);

        n4P.setBackground(white);
        n4.setForeground(clkColor);

        n5P.setBackground(white);
        n5.setForeground(clkColor);

        n6P.setBackground(white);
        n6.setForeground(clkColor);

        n7P.setBackground(white);
        n7.setForeground(clkColor);

        n8P.setBackground(white);
        n8.setForeground(clkColor);

        n9P.setBackground(white);
        n9.setForeground(clkColor);

        clrP.setBackground(white);
        clr.setForeground(clkColor);

        delP.setBackground(white);
        del.setForeground(clkColor);
    }//GEN-LAST:event_n0MousePressed

    private void delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delMouseClicked
        // TODO add your handling code here:
        if(num.getText().length() > 0)
        {
            String txt = num.getText();
            String txtMinus = txt.substring(0, txt.length() - 1);
            num.setText(txtMinus);
        }
    }//GEN-LAST:event_delMouseClicked

    private void delMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delMousePressed
        // TODO add your handling code here:
        clrP.setBackground(white);
        clr.setForeground(clkColor);

        delP.setBackground(clkColor);
        del.setForeground(white);

        n0P.setBackground(white);
        n0.setForeground(clkColor);

        n1P.setBackground(white);
        n1.setForeground(clkColor);

        n2P.setBackground(white);
        n2.setForeground(clkColor);

        n3P.setBackground(white);
        n3.setForeground(clkColor);

        n4P.setBackground(white);
        n4.setForeground(clkColor);

        n5P.setBackground(white);
        n5.setForeground(clkColor);

        n6P.setBackground(white);
        n6.setForeground(clkColor);

        n7P.setBackground(white);
        n7.setForeground(clkColor);

        n8P.setBackground(white);
        n8.setForeground(clkColor);

        n9P.setBackground(white);
        n9.setForeground(clkColor);
    }//GEN-LAST:event_delMousePressed

    private void clrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrMouseClicked
        // TODO add your handling code here
        num.setText("");
    }//GEN-LAST:event_clrMouseClicked

    private void clrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrMousePressed
        // TODO add your handling code here:
        clrP.setBackground(clkColor);
        clr.setForeground(white);

        delP.setBackground(white);
        del.setForeground(clkColor);

        n0P.setBackground(white);
        n0.setForeground(clkColor);

        n1P.setBackground(white);
        n1.setForeground(clkColor);

        n2P.setBackground(white);
        n2.setForeground(clkColor);

        n3P.setBackground(white);
        n3.setForeground(clkColor);

        n4P.setBackground(white);
        n4.setForeground(clkColor);

        n5P.setBackground(white);
        n5.setForeground(clkColor);

        n6P.setBackground(white);
        n6.setForeground(clkColor);

        n7P.setBackground(white);
        n7.setForeground(clkColor);

        n8P.setBackground(white);
        n8.setForeground(clkColor);

        n9P.setBackground(white);
        n9.setForeground(clkColor);
    }//GEN-LAST:event_clrMousePressed

    private void entrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrMouseClicked
        // TODO add your handling code here:
       // BillingSystem1 transNum = new BillingSystem1();
       // transNum.csh.setText(num.getText());
       // this.dispose();
    }//GEN-LAST:event_entrMouseClicked

    private void entrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrMousePressed

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clr;
    private javax.swing.JPanel clrP;
    private javax.swing.JLabel del;
    private javax.swing.JPanel delP;
    public javax.swing.JLabel entr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel n0;
    private javax.swing.JPanel n0P;
    private javax.swing.JPanel n0P1;
    private javax.swing.JLabel n1;
    private javax.swing.JPanel n1P;
    private javax.swing.JLabel n2;
    private javax.swing.JPanel n2P;
    private javax.swing.JLabel n3;
    private javax.swing.JPanel n3P;
    private javax.swing.JLabel n4;
    private javax.swing.JPanel n4P;
    private javax.swing.JLabel n5;
    private javax.swing.JPanel n5P;
    private javax.swing.JLabel n6;
    private javax.swing.JPanel n6P;
    private javax.swing.JLabel n7;
    private javax.swing.JPanel n7P;
    private javax.swing.JLabel n8;
    private javax.swing.JPanel n8P;
    private javax.swing.JLabel n9;
    private javax.swing.JPanel n9P;
    private javax.swing.JTextField num;
    // End of variables declaration//GEN-END:variables
}
