/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalsproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author LAURO ANTONIO
 */
public class LogIn extends javax.swing.JFrame {

    /* static void setVisivle(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }*/
    /**
     * Creates new form LogIn
     */
    Color clkColor, white;

    public LogIn() {
        initComponents();
        clkColor = new Color(76, 44, 23);
        white = new Color(255, 255, 255);
        pWord.setEchoChar('•');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        uName = new javax.swing.JTextField();
        pWord = new javax.swing.JPasswordField();
        showPass = new javax.swing.JCheckBox();
        lgInP = new javax.swing.JPanel();
        lgIn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CashierLogin");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 400));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(76, 44, 23));
        jPanel3.setMaximumSize(new java.awt.Dimension(346, 400));
        jPanel3.setMinimumSize(new java.awt.Dimension(346, 400));
        jPanel3.setPreferredSize(new java.awt.Dimension(344, 400));
        jPanel3.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FinalLogo (2).png"))); // NOI18N
        jLabel2.setName(""); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(70, 20, 220, 199);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cofLogo/kopibg (3).png"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(-20, 280, 370, 141);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(167, 146, 119));
        jLabel3.setText("There’s always peace in a strong cup of coffee.");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 240, 260, 15);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(167, 146, 119));
        jLabel5.setText("It doesn’t matter where you’re from – or how you feel… ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 220, 300, 15);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 344, 400);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 44, 23));
        jLabel1.setText("Log In");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(470, 40, 108, 38);

        uName.setFont(new java.awt.Font("Raavi", 0, 16)); // NOI18N
        uName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(183, 183, 184)), "Username", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N
        uName.setPreferredSize(new java.awt.Dimension(250, 50));
        uName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameActionPerformed(evt);
            }
        });
        jPanel2.add(uName);
        uName.setBounds(397, 131, 250, 50);

        pWord.setFont(new java.awt.Font("Raavi", 0, 16)); // NOI18N
        pWord.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(183, 183, 184)), "Password", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N
        pWord.setMinimumSize(new java.awt.Dimension(54, 64));
        pWord.setPreferredSize(new java.awt.Dimension(250, 50));
        pWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pWordActionPerformed(evt);
            }
        });
        jPanel2.add(pWord);
        pWord.setBounds(397, 187, 250, 50);

        showPass.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        showPass.setForeground(new java.awt.Color(98, 94, 94));
        showPass.setText("Show Password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        jPanel2.add(showPass);
        showPass.setBounds(546, 243, 101, 19);

        lgInP.setBackground(new java.awt.Color(76, 44, 23));
        lgInP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 44, 23)));
        lgInP.setPreferredSize(new java.awt.Dimension(85, 33));

        lgIn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        lgIn.setForeground(new java.awt.Color(255, 255, 255));
        lgIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgIn.setText("Log In");
        lgIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lgIn.setPreferredSize(new java.awt.Dimension(85, 33));
        lgIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgInMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lgInMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lgInMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout lgInPLayout = new javax.swing.GroupLayout(lgInP);
        lgInP.setLayout(lgInPLayout);
        lgInPLayout.setHorizontalGroup(
            lgInPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lgInPLayout.createSequentialGroup()
                .addComponent(lgIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        lgInPLayout.setVerticalGroup(
            lgInPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        jPanel2.add(lgInP);
        lgInP.setBounds(478, 274, 85, 31);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/beans/bean4.png"))); // NOI18N
        jLabel8.setName(""); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(430, 0, 50, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getEmployeeId(String emName, String emID) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3325/finalsproject", "root", "");
            Statement statement = connection.createStatement();

            String emplo = "SELECT * FROM `employe` WHERE GivenName = '" + emName + "'";
            statement.execute(emplo);

            ResultSet rsemplo = statement.executeQuery(emplo);

            while (rsemplo.next()) {
                emID = rsemplo.getString("EmployeeID");
                emName = rsemplo.getString("GivenName");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            System.out.println("Error!" + e.getMessage());
        }
    }
    private void uNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameActionPerformed

    private void pWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pWordActionPerformed

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        // TODO add your handling code here:
        if (showPass.isSelected()) {
            pWord.setEchoChar((char) 0);
        } else {
            pWord.setEchoChar('•');
        }
    }//GEN-LAST:event_showPassActionPerformed

    private void lgInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgInMouseClicked

        String emplo, Password, query1, query2, fname = null, passDb = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3325/finalsproject", "root", "");
            Statement statement = connection.createStatement();

            if ("".equals(uName.getText())) {
                JOptionPane.showMessageDialog(null, "Username is empty", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(pWord.getText())) {
                JOptionPane.showMessageDialog(null, "Password is require", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (Integer.valueOf(pWord.getText().length()) < 8) {
                JOptionPane.showMessageDialog(null, "Your password needs to be atleast 8 characters", "message", ERROR_MESSAGE);
            } else {
                emplo = uName.getText();
                Password = pWord.getText();

                query1 = "SELECT * FROM `employee` WHERE GivenName = '" + emplo + "'";
                int f1 = 0, f2 = 0;
                ResultSet rs1 = statement.executeQuery(query1);
                while (rs1.next()) {
                    fname = rs1.getString("GivenName");
                    f1 = 1;
                }

                query2 = "SELECT * FROM `employee` WHERE EmployeeID = '" + Password + "'";

                ResultSet rs2 = statement.executeQuery(query2);
                while (rs2.next()) {
                    passDb = rs2.getString("EmployeeID");
                    f2 = 1;
                }

                if (emplo.equals(fname) && Password.equals(passDb)) {
                    BillingSystem1 BilSys = new BillingSystem1();
                    String wc = "Welcome " + emplo + "!!";
                    BilSys.wel.setText(String.valueOf(wc));
                    BilSys.cashier.setText(String.valueOf(emplo));
                    if (emplo.equals("James")) {
                        BilSys.emploImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\James\\Downloads\\JIM.jpg"));
                    } else if (emplo.equals("Edward")) {
                        BilSys.emploImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\James\\Downloads\\ed (1).jpg"));
                    } else if (emplo.equals("Lawrence")) {
                        BilSys.emploImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\James\\Downloads\\law (1).jpg"));
                    } else if (emplo.equals("Bryan")) {
                        BilSys.emploImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\James\\Downloads\\bj (1).jpg"));
                    } else if (emplo.equals("Jhonny")) {
                        BilSys.emploImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\James\\Downloads\\jasper (1).jpg"));
                    } else {
                        System.out.print("Employee Image doesn't found");
                    }
                    BilSys.setVisible(true);
                    BilSys.pack();
                    BilSys.setLocationRelativeTo(null);
                    this.dispose();
                } else if (f1 == 0 && Password.equals(passDb)) {
                    JOptionPane.showMessageDialog(null, "Incorrect username", "message", ERROR_MESSAGE);
                    uName.setText("");
                } else if (emplo.equals(fname) && f2 == 0) {
                    JOptionPane.showMessageDialog(null, "Incorrect password", "message", ERROR_MESSAGE);
                    pWord.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Account not found", "message", ERROR_MESSAGE);
                    uName.setText("");
                    pWord.setText("");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lgInMouseClicked

    private void lgInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgInMousePressed
        // TODO add your handling code here:
        lgInP.setBackground(white);
        lgIn.setForeground(clkColor);
    }//GEN-LAST:event_lgInMousePressed

    private void lgInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgInMouseReleased
        // TODO add your handling code here:
        lgInP.setBackground(clkColor);
        lgIn.setForeground(white);
    }//GEN-LAST:event_lgInMouseReleased

    private void lgInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgInMouseEntered
        // TODO add your handling code here:
        lgInP.setBackground(clkColor);
        lgIn.setForeground(white);
    }//GEN-LAST:event_lgInMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRANFER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRANFER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRANFER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRANFER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                LogIn LgIn = new LogIn();
                //new LogIn().setVisible(true);
                LgIn.setVisible(true);
                LgIn.pack();
                LgIn.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lgIn;
    private javax.swing.JPanel lgInP;
    private javax.swing.JPasswordField pWord;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JTextField uName;
    // End of variables declaration//GEN-END:variables
}
